### ISSUE TITLE
Work together on eslint-config-defaults

### ISSUE THREAD

**Issue by baer** [reactjs/eslint-config-reactjs#6]
Hello! I wanted to propose a collaboration between this repo and https://github.com/walmartlabs/eslint-config-defaults.

I originally set out to build config-defaults because I was tired of copy pasting my eslint config around and trying to keep them up to date across lots of projects. Eslint's `extends` key fixes the distribution problem but there were still two issues:

1. Managing the eslint config file was a pain in the ass even though it was now centralized.
2. Just get up and running for a new project was not straightforward and I strongly believe that code quality tooling should be well suited to those who are just starting out. They're often the ones who need it most after all.

So with this project I centralized a few configs from major players to help anybody get up and running easily, I committed to staying on top of the latest rules (and deprecations) and most importantly I made the config composable which allows them to be easily mixed and matched!

---

I'd love to pull this config into my project. In fact it's already been requested. Rather than create an "unofficial" rackt config I'd like to ask if you'd be interested in working together?

**Comment by taion** [comment]
cc @mjackson

**Comment by mjackson** [comment]
Hi @baer :) I don't fully understand what you're doing with config-defaults. What is the benefit of having composable eslint configs? Wouldn't they conflict with one another?

**Comment by baer** [comment]
Hi @mjackson! Thanks for getting back to me. Also, thanks for all of the great things you continue to do in OSS. 

The idea with composable lint configs is more or less the same idea with composable code:

* Small things with a single purpose are easier to do well than big things
* Less of the "Gorilla Banana Problem"

What I mean by this is that if you want to compose the configs into lots of specific use cases (es5-browser, es5-node, es6, es6-node4, es6-node5 etc.) as many projects do you are free to do so. For an example, you can have a look at what [walmartlabs is doing to their 100k+ of JavaScript here](https://github.com/walmartlabs/eslint-config-defaults/tree/master/configurations/walmart).

The consolidation bit of this is more of a nicety. ESLint is in my opinion an objectively better linter but because it is a bit harder to configure it is still playing second fiddle to JSHint is a lot of places. It was my hope that by consolidating a few really solid and well maintained config files in one place it could make this a bit more beginner friendly.

The final bit is that nobody wants to maintain configs - especially when people are doing OSS out of the goodness of their hearts in the first place. The final reason for this project is that I can commit to follow the ESLint releases and keep the config as up to date as possible.

Hope that answers your question.

**Comment by taion** [comment]
@baer BTW, we might move toward deprecating this ESLint config anyway: https://github.com/reactjs/eslint-config-reactjs/issues/8

**Comment by mjackson** [comment]
Ya, I think one of our goals in the short term is to get rid of this repo altogether and use one of the more widely used standard configs.

**Comment by baer** [comment]
Sounds good. Thanks again. Feel free to close the issue

**Comment by taion** [comment]
Thanks!
